### ISSUE TITLE
Use SQLCipher or something like that

### ISSUE THREAD

**Issue by cjeanneret** [savoirfairelinux/sflvault#25]
Hello,

It might be better for security to completely encrypt the sqlite database. For example using [SQLCipher](https://www.zetetic.net/sqlcipher/open-source/).

Of course, if an attacker gets hand on the db file, this means he might get hand on the SQLCipher settings — but it doesn't cost much to ensure all is properly encrypted from the very base.

Cheers,

C.

**Comment by hsoft** [comment]
Secrets held in the DB are already encrypted by the client. The server itself cannot access to plain secrets, only clients, with their private key, can.

**Comment by hsoft** [comment]
To be more precise, it's actually, the *groups* private key that is used to encrypt the secret, but this key is not stored plainly in the DB, it's encrypted using each member's public key. See http://sflvault.org/architecture.html#cryptographic-scheme-overview for details.

**Comment by cjeanneret** [comment]
Yup, I was pretty sure the content itself is encrypted. SQLCipher adds some more crypto (I just see I didn't write down a part of a sentence telling something like "the content is already encrypted").

Anyway, feel free to mark it as invalid if needed — sqlcipher (or else) could have masked as well the username and other plain-text (thus not sensitive) data ;).

**Comment by Apteryks** [comment]
I'll close this as this doesn't appear to fit the security model of SFLVault (see: https://sflvault.org/architecture.html#cryptographic-scheme-overview as mentioned earlier), which is known as sound.
