### ISSUE TITLE
Not compatible with Python 3

### ISSUE THREAD

**Issue by Apteryks** [savoirfairelinux/sflvault#27]
Currently it can be installed from pip on Python 3, but it crashes due to use of Python 2 syntax.

Python 2 is nearing end of life (planned for 2020).

**Comment by support-savoirfairelinux** [comment]
The Python 3 port of sflvault-client has now been merged into master. We should still bump the version, tag and release on PyPI, so leaving open to track this.

**Comment by Apteryks** [comment]
There has been a new release on PyPI, closing.
