### ISSUE TITLE
let the user skip validation for ssl certificates

### ISSUE THREAD

**Issue by llacroix** [savoirfairelinux/sflvault#7]
When sflvault tries to connect to a vault with an expired certificate. It might fail without much information on how to solve the problem.

Here's a change that will not verify the certificates. It could be handled differently. For example, it could come as a configuration in ~/.sflvault/config

        context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
        context.verify_mode = ssl.CERT_NONE 
        url = self.cfg.get('SFLvault', 'url')
        if url:
            self.vault = xmlrpclib.Server(url, allow_none=True, context=context).sflvault

**Comment by ReAzem** [comment]
I don't know if its related, but this is the error I am getting:
```
[SFLvault] Cannot connect to the vault: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

So this might be because the certificate of our vault is expired or invalid.

**Comment by llacroix** [comment]
@ReAzem It's related. I can't really explain the issue here. But it's related to the certificate. This is a bug I had. It might depend of your SSL lib that block or doesn't block invalid certificates by default.

**Comment by ReAzem** [comment]
typo: #17 fixed it for me.

**Comment by llacroix** [comment]
I guess it's fine then I'll close the issue.

**Comment by ReAzem** [comment]
Maybe its time for a release then? This fix isn't available in pypi
